export const LOGIN = {
  INITIAL_STATE: 'INITIAL_STATE',
  SUBMIT_LOGIN: 'SUBMIT_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};

export const SIGNUP = {
  INITIAL_STATE: 'INITIAL_STATE',
  SUBMIT_SIGNUP: 'SUBMIT_SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
};