export const LOGIN = {
  INITIAL_STATE: 'INITIAL_STATE',
  SUBMIT_LOGIN: 'SUBMIT_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};

export const SIGNUP = {
  INITIAL_STATE: 'INITIAL_STATE',
  SUBMIT_SIGNUP: 'SUBMIT_SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
};

export const SUGGEST_FRIENDS = {
  INITIAL_STATE: 'INITIAL_STATE',
  GET_USER_LIST: 'FETCH_USER_LIST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAIL: 'GET_USER_FAIL',
  ADD_FRIEND_REQUEST: 'ADD_FRIEND_REQUEST',
  ADD_FRIEND_SUCCESS: 'ADD_FRIEND_SUCCESS',
  ADD_FRIEND_FAIL: 'ADD_FRIEND_FAIL',
  ACCEPT_FRIEND_REQUEST: 'ACCEPT_FRIEND_REQUEST',
  ACCEPT_FRIEND_SUCCESS: 'ACCEPT_FRIEND_SUCCESS',
  DECLINED_FRIEND_REQUEST: 'DECLINED_FRIEND_REQUEST',
  DECLINED_FRIEND_SUCCESS: 'DECLINED_FRIEND_SUCCESS',
  CANCEL_FRIEND_REQUEST: 'CANCEL_FRIEND_REQUEST',
  CANCEL_FRIEND_SUCCESS: 'CANCEL_FRIEND_SUCCESS',
  ADD_USER_TO_REQUEST_FRIENDS: 'ADD_USER_TO_REQUEST_FRIENDS',
  REMOVE_USER_IN_REQUEST_FRIENDS: 'REMOVE_USER_IN_REQUEST_FRIENDS',
};

export const USER = {
  INITIAL_STATE: 'INITIAL_STATE',
  GET_INFO_USER: 'GET_INFO_USER',
  GET_INFO_USER_SUCCESS: 'GET_INFO_USER_SUCCESS',
  GET_INFO_USER_FAIL: 'GET_INFO_USER_FAIL',
  CONNECT_SOCKET: 'CONNECT_SOCKET',
  DISCONNECT_SOCKET: 'DISCONNECT_SOCKET',
};