export const LOGIN = {
  INITIAL_STATE: 'INITIAL_STATE',
  SUBMIT_LOGIN: 'SUBMIT_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};

export const SIGNUP = {
  INITIAL_STATE: 'INITIAL_STATE',
  SUBMIT_SIGNUP: 'SUBMIT_SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
};

export const EVERYBODY = {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAIL: 'GET_USER_FAIL',
};

export const FRIENDS = {
  GET_FRIENDS: 'GET_ALL_FRIEND',
  GET_FRIEND_SUCCESS: 'GET_FRIEND_SUCCESS',

  GET_FRIEND_INVITATION: 'GET_FRIEND_INVITATION',
  GET_FRIEND_INVITATION_SUCCESS: 'GET_FRIEND_INVITATION_SUCCESS',

  GET_FRIEND_REQUEST: 'GET_FRIEND_REQUEST',
  GET_FRIEND_REQUEST_SUCCESS: 'GET_FRIEND_REQUEST_SUCCESS',

  ADD_FRIEND_REQUEST: 'ADD_FRIEND_REQUEST',
  ADD_FRIEND_SUCCESS: 'ADD_FRIEND_SUCCESS',
  ADD_FRIEND_FAIL: 'ADD_FRIEND_FAIL',

  TOGGLE_MODAL_ERROR: 'TOGGLE_MODAL_ERROR',

  ACCEPT_FRIEND_REQUEST: 'ACCEPT_FRIEND_REQUEST',
  ACCEPT_FRIEND_SUCCESS: 'ACCEPT_FRIEND_SUCCESS',
  ACCEPT_FRIEND_FAIL: 'ACCEPT_FRIEND_FAIL',

  DECLINED_FRIEND_REQUEST: 'DECLINED_FRIEND_REQUEST',
  DECLINED_FRIEND_SUCCESS: 'DECLINED_FRIEND_SUCCESS',

  CANCEL_FRIEND_REQUEST: 'CANCEL_FRIEND_REQUEST',
  CANCEL_FRIEND_SUCCESS: 'CANCEL_FRIEND_SUCCESS',

  REMOVE_FRIEND_REQUEST: 'REMOVE_FRIEND_REQUEST',
  REMOVE_FRIEND_SUCCESS: 'REMOVE_FRIEND_SUCCESS',

  ADD_USER_TO_REQUEST_FRIENDS: 'ADD_USER_TO_REQUEST_FRIENDS',
  REMOVE_USER_IN_REQUEST_FRIENDS: 'REMOVE_USER_IN_REQUEST_FRIENDS',
};

export const USER = {
  INITIAL_STATE: 'INITIAL_STATE',

  GET_MY_PROFILE_REQUEST: 'GET_MY_PROFILE_REQUEST',
  GET_MY_PROFILE_SUCCESS: 'GET_MY_PROFILE_SUCCESS',

  GET_INFO_USER_REQUEST: 'GET_INFO_USER_REQUEST',
  GET_INFO_USER_SUCCESS: 'GET_INFO_USER_SUCCESS',

  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',

  TOGGLE_MODAL_UPDATE_PROFILE_FAIL: 'TOGGLE_MODAL_UPDATE_PROFILE_FAIL',
  CONNECT_SOCKET: 'CONNECT_SOCKET',
  DISCONNECT_SOCKET: 'DISCONNECT_SOCKET',
  LOG_OUT: 'LOG_OUT',
};